### ISSUE TITLE
Prefer map over collect ?

### ISSUE THREAD

**Issue by akash2504** [airbnb/ruby#101]
This style guide says that we should prefer map over collect. but this link (http://rubyinrails.com/2014/01/25/ruby-difference-between-collect-and-map/) clearly explains that in ruby there is no difference between map and collect. Then why to prefer map?
Am i missing something?

**Comment by ljharb** [comment]
Preferring one over the other helps maintain consistency - in the common case of there being multiple aliases for the same function, it's a best practice to select one variant, and require that be the one used.

In regard to this specific case, imo `map` is a more common idiom for "transform one array into another", and as such, that name is less confusing than the much rarer "collect".

**Comment by tommydangerous** [comment]
+1 to @ljharb

**Comment by akash2504** [comment]
We should mention this in the style guide. Having the statement Prefer map over collect gives a sense that the implementation of two is different and former is better over latter. Isn't it?

**Comment by ljharb** [comment]
I both agree that more explanation would be better, and disagree that the current statement implies anything of the sort whatsoever.

**Comment by harry-wood** [comment]
Also in the ruby style guide: https://rubystyle.guide/#map-find-select-reduce-size 

_"Prefer `map` over `collect`. ... This is not a hard requirement; if the use of the alias enhances readability, it’s ok to use it "_
