### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by ryanclark2** [airbnb/ruby#112]
Hello, 

I'd like to use this style guide as a basis to start our own for my team, but there's no license information and I don't want to step on toes. Can someone please specify how this is made available? 

Thanks!

**Comment by 0x414f** [comment]
Same question. Any comment here?

**Comment by ljharb** [comment]
This should be MIT; #133 will address that.

**Comment by ryanclark2** [comment]
Boom! Made it just before the 1-year mark :) Thanks folks!
