### ISSUE TITLE
Kali Linux ruby upgrade error

### ISSUE THREAD

**Issue by alfrego129** [airbnb/ruby#125]
My problem is that

I use Kali Linux and I am trying to use the tool of "beef", however, for this ,I need to upgrade ruby because I see this error

'Ruby version 2.1.5 is no longer supported. Please upgrade to Ruby version 2.2 or later.'
When I check my version of the ruby it is 'ruby 2.1.5p273 (2014-11-13) [i386-linux-gnu]'.

And then I tried respectively

sudo apt-get install ruby2.0

sudo apt-get install ruby-full

apt-get upgrade

apt-get update
But still I could not upgrade it, how can I upgrade, could you help me, please?

Thank you.

**Comment by BMorearty** [comment]
I'm sorry, this is a Ruby style guide. This is not a place for Ruby support.
