### ISSUE TITLE
Broken link on http://airbnb.io/projects/ruby/

### ISSUE THREAD

**Issue by nodanaonlyzuul** [airbnb/ruby#128]
Hullo.

Firstly, thanks for the hard work and sharing your style guides.
http://airbnb.io/projects/ruby/ link to the Google C++ style guide is broken (http://google-styleguide.googlecode.com/svn/trunk/cppguide.xml).

The C++ guide now lives here: https://google.github.io/styleguide/cppguide.html

I know http://airbnb.io/projects/ruby/ isn't governed by this repo but that page links to this repo under the "start a convo" button. I did a bit of digging to find the repo containing the source for airbnb.io but couldn't find it. 

Let me know if there's a more appropriate repo for this ticket and again THANKS!

**Comment by aamarill** [comment]
Hello,

I am looking to make my first open source contribution. Is this a good issue to take on?
If not, feel free to point me other issues that might be good for someone that's new to open source.
Thanks!

**Comment by ljharb** [comment]
@aamarill sure, that'd be great, thanks

**Comment by aamarill** [comment]
@ljharb can you please let me know where the repo for [https://airbnb.io/projects/ruby/](https://airbnb.io/projects/ruby/) is? I couldn't find it, I also read the "CONTRIBUTING.md" and couldn't find anything on the repo. Thanks!

**Comment by ljharb** [comment]
ah, turns out this was already fixed in #105, but hasn't been updated in the private repo for airbnb.io.

I'll pursue this internally.

**Comment by nodanaonlyzuul** [comment]
Hi @ljharb !

I'm going to close this ticket if the repo that governs that static site is private and trust you to open up a ticket in that repo.  Thanks to you and @aamarill for looking into this ticket.
