### ISSUE TITLE
Method chaining

### ISSUE THREAD

**Issue by kiriakosv** [airbnb/ruby#130]
Hello, is there a rule regarding method chaining? For example:
```ruby
person = Person.new

# bad
person.name("Peter").age(21).introduce

# good
person.name("Peter")
      .age(21)
      .introduce
```

If not, can I make a pull request to add one?

**Comment by BMorearty** [comment]
@kiriakosv Thank you for offering to contribute.

We allow method chaining within the same line. And we generally put the dot at the end of the line when we break it up across lines.
