### ISSUE TITLE
Could you clarify why there is many disabled cops?

### ISSUE THREAD

**Issue by smennesson** [airbnb/ruby#149]
Hello,

first of all thank you to share this project.

I'd like to use the `rubocop-airbnb` gem in my projects but I'm wondering why there is many Rubocop cops disabled by default.

When I'm looking in the `rubocop-airbnb/config` folder, I can find 288 disabled cops.

For some of these cops, the disabling reason is documented. But for some others (a majority I guess), this is not the case.

Here are some examples of disabled cops for which I can't find the disabling reason:
* Metrics/MethodLength
* Metrics/PerceivedComplexity
* Naming/ConstantName
* Naming/MethodName
* Bundler/OrderedGems

Will all these disabled cops, I'm feeling like loosing some checks that are done by Rubocop by default.

Kind regards,
Stéphane

**Comment by BMorearty** [comment]
Hi Stéphane,

I'm sorry to take so long to answer this. Rubocop has hundreds of cops that are available to choose from. It's up to a team's judgment to decide which ones they think should be used. I don't know the full history of why some have a rationale given and some don't. If you want to, you can still use this gem but supplement it by enabling or disabling additional cops.
