### ISSUE TITLE
RiskyActiverecordInvocation false positive

### ISSUE THREAD

**Issue by sk-** [airbnb/ruby#153]
`File.exists?` should not be flagged by `RiskyActiverecordInvocation`.

**Comment by ljharb** [comment]
It's probably impossible to statically differentiate in `x.exists?` between `x` being a file or an activerecord object.

**Comment by sk-** [comment]
@ljharb Agree, but at least you could whitelist `File.exists?` where `File` is the ruby class and not a variable. That was the reported issue about, sorry if it wasn't clear.

Also, even in the case `file.exists?` you could apply some heuristics to decide whether the first parameter corresponds to SQL or not.

**Comment by BMorearty** [comment]
Luckily for us, `File.exists?` [is deprecated in favor of `File.exist?`](https://ruby-doc.org/core-2.2.0/File.html#method-c-exists-3F) so I don't think it's necessary to do any work to accommodate it.

The docs say "Deprecated method. Don't use."
