### ISSUE TITLE
Any prediction on when a version will be released?

### ISSUE THREAD

**Issue by josemiguelmelo** [airbnb/ruby#176]
Hi,

I noticed you're not releasing a new version on RubyGems for quite some time.
Do you have any predictions on when you're going to make the release?

Thanks,

**Comment by pariser** [comment]
Hey @josemiguelmelo thanks for asking, I think we'll look to getting a new release out in mid-late October. Sorry about the general lack of activity on this repository recently, we haven't changed our style guide recently.

**Comment by aguynamedben** [comment]
Bump... we'd like to use airbnb-rubocop with Rubocop 0.80.1 and Code Climate.

FWIW Rubocop is on version 1.8.1 now. The latest version of this library requires `~> 0.76.0`, which is pretty old now. Maybe the dependency on Rubocop version can be relaxed?

**Comment by pariser** [comment]
❤️ @aguynamedben totally understood, and apologies for not actually getting to this when we were hoping to. I'm regrouping with a few folks tomorrow to see if anyone can _actively_ work on this and what their time frame would be.

**Comment by aguynamedben** [comment]
No worries, we love the project, just a friendly bump!

**Comment by ericatripp** [comment]
we would love this as well.  it's currently blocking us from upgrading to ruby 3.0, and we'd love to have both.  thanks for making a great package ❤️

**Comment by ericatripp** [comment]
any update on timeline here @pariser?

**Comment by pariser** [comment]
Hey everyone, I know this is a _long_ time coming, but I just started working on https://github.com/airbnb/ruby/pull/181. I'm not sure I've gotten everything done to release a new version yet, but it's a good start. If you'd like to help advance this along, I'd love some reviews from the community!
