### ISSUE TITLE
Ruby 3.1.3

### ISSUE THREAD

**Issue by Amnesthesia** [airbnb/ruby#187]
This gem depends on such an outdated version of Rubocop, which is now at 1.39.0, that we're unable to use it with Ruby 3.1.3

Any chance this gem will be updated to support Ruby >= 3.1.3 (and a more recent rubocop version)?

**Comment by pariser** [comment]
https://github.com/airbnb/ruby/pull/189 added support for Ruby3.1 and in https://github.com/airbnb/ruby/pull/192 it was released as version `5.0.0`!
