### ISSUE TITLE
The negation operator

### ISSUE THREAD

**Issue by RomanMenzel** [airbnb/ruby#50]
When I try to use the negation operator without parens, it doesn't work!
With which ruby version did you try the examples?

**Comment by ljharb** [comment]
Can you provide a code example? `x = 3; -x` prints out negative three in every ruby console I've ever used.

**Comment by RomanMenzel** [comment]
No, I mean the '!' operator. An example would be:
```ruby
if !x == 3
...
end
```
This doesn't work! :point_up:

**Comment by ljharb** [comment]
You want `if x != 3` there. negation applies to a value, and `!x` will never == 3, because `!x` will always be a boolean `true` or `false`.

**Comment by RomanMenzel** [comment]
Ok, now I understand, thank you.
