### ISSUE TITLE
Link to rule

### ISSUE THREAD

**Issue by venantius** [airbnb/ruby#75]
One of the awesome things about bbatsov's guide is that each rule is accompanied by a link to that particular rule, so that you can easily reference it in a discussion. We should do the same thing here!

**Comment by robotpistol** [comment]
:100:

**Comment by tommydangerous** [comment]
@venantius What do you mean link? From the header to the section or from the rule to the explanation or rationale?

**Comment by venantius** [comment]
I mean including the "[link]" thing per bbatsov's guide:
<img width="602" alt="screen shot 2016-02-11 at 9 22 09 pm" src="https://cloud.githubusercontent.com/assets/1824859/12999566/92ec7372-d105-11e5-92e3-0c29424c94ac.png">

**Comment by tommydangerous** [comment]
^ I like that

**Comment by BMorearty** [comment]
Giddyup. I thought this had already been suggested somewhere but I don't see it. I love it.

**Comment by venantius** [comment]
Cool. I'll start working on a PR for this now (just announcing to keep anyone else from duplicating what seems likely to be rote/unfun work)
