### ISSUE TITLE
Shorten example code

### ISSUE THREAD

**Issue by venantius** [airbnb/ruby#80]
A lot of our sample code blocks are longer than they need to be to get the point across. I think we could do with cleaning these up a bit. The 100-char line limit addressed in #77 is but one example of this. 

Discuss.

**Comment by tommydangerous** [comment]
I agree.

**Comment by tommydangerous** [comment]
Another thing I would like to clean up is move the bad examples above the good examples and make it consistent throughout.

**Comment by venantius** [comment]
Omg @tommydangerous ++++++ agree so hard.

**Comment by tommydangerous** [comment]
Luckily, I only found 2 violations: https://github.com/airbnb/ruby/pull/84

**Comment by ljharb** [comment]
+1, examples should be long enough to clearly illustrate the point (and ideally should encompass commonly used patterns) but no longer.

**Comment by robotpistol** [comment]
I'm closing this as the examples are shorter than 100 characters now.
