### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by snood1205** [airbnb/ruby#97]
There is no style advice on `attr_accessor`, `attr_reader`, or `attr_writer`. Can this be added?

**Comment by BMorearty** [comment]
@snood1205 I think the reason for no style advice is there's nothing to say about it, style-wise. What would you want a style guide to say?

**Comment by tommydangerous** [comment]
I agree with @bmorearty, the only advice I can think of is if you have the same attribute for attr reader and writer and they are both public, private, or protected then DRY it up and use attr accessor. But this seems common sense.
